name: Abdul Music Bot
on:
  push:
    branches:
      - master

jobs:
  build-and-deploys:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: asia.gcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          tags: asia.gcr.io/scamo-group/abdul-gg/discord-music-bot
      - uses: deploys-app/deploys-action@v1
        with:
          project: abdul-gg
          location: gke.cluster-rcf2
          name: discord-music-bot
          image: asia.gcr.io/scamo-group/abdul-gg/discord-music-bot@${{ steps.docker_build.outputs.digest }}
        env:
          DEPLOYS_AUTH_USER: ${{ secrets.DEPLOYS_AUTH_USER }}
          DEPLOYS_AUTH_PASS: ${{ secrets.DEPLOYS_AUTH_PASS }}
